package com.tantan.mydata.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tantan.mydata.greendao.StudyColor;
import com.tantan.mydata.greendao.StudyObject;
import com.tantan.mydata.greendao.UserInfoEntity;

import com.tantan.mydata.greendao.StudyColorDao;
import com.tantan.mydata.greendao.StudyObjectDao;
import com.tantan.mydata.greendao.UserInfoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studyColorDaoConfig;
    private final DaoConfig studyObjectDaoConfig;
    private final DaoConfig userInfoEntityDaoConfig;

    private final StudyColorDao studyColorDao;
    private final StudyObjectDao studyObjectDao;
    private final UserInfoEntityDao userInfoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studyColorDaoConfig = daoConfigMap.get(StudyColorDao.class).clone();
        studyColorDaoConfig.initIdentityScope(type);

        studyObjectDaoConfig = daoConfigMap.get(StudyObjectDao.class).clone();
        studyObjectDaoConfig.initIdentityScope(type);

        userInfoEntityDaoConfig = daoConfigMap.get(UserInfoEntityDao.class).clone();
        userInfoEntityDaoConfig.initIdentityScope(type);

        studyColorDao = new StudyColorDao(studyColorDaoConfig, this);
        studyObjectDao = new StudyObjectDao(studyObjectDaoConfig, this);
        userInfoEntityDao = new UserInfoEntityDao(userInfoEntityDaoConfig, this);

        registerDao(StudyColor.class, studyColorDao);
        registerDao(StudyObject.class, studyObjectDao);
        registerDao(UserInfoEntity.class, userInfoEntityDao);
    }
    
    public void clear() {
        studyColorDaoConfig.clearIdentityScope();
        studyObjectDaoConfig.clearIdentityScope();
        userInfoEntityDaoConfig.clearIdentityScope();
    }

    public StudyColorDao getStudyColorDao() {
        return studyColorDao;
    }

    public StudyObjectDao getStudyObjectDao() {
        return studyObjectDao;
    }

    public UserInfoEntityDao getUserInfoEntityDao() {
        return userInfoEntityDao;
    }

}
